language: python
sudo: true
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - 3.6
    - pypy
install:
    - pip install -r requirements-dev.txt
    - pip install -r requirements.txt
    - pip install codecov pytest-cov
script:
    - env PYTHONPATH=. py.test -v --cov=./ tests
    - python setup.py install
    - py.test -v tests
after_success:
    - codecov
