language: python
sudo: true
env:
    - INSTALL_TYPE=no PYTHONPATH=.
    - INSTALL_TYPE=direct
    - INSTALL_TYPE=git
    - INSTALL_TYPE=pypi
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - 3.6
    - pypy
    - pypy3
install:
    - if [[ "${INSTALL_TYPE}" == "no" ]]; then pip install -r requirements.txt; fi
    - if [[ "${INSTALL_TYPE}" == "direct" ]]; then python setup.py install; fi
    - if [[ "${INSTALL_TYPE}" == "git" ]]; then pip install https://github.com/MrLYC/IFV/archive/master.zip; fi
    - if [[ "${INSTALL_TYPE}" == "pypi" ]]; then pip install ifv; fi
    - pip install -r requirements-dev.txt
    - pip install codecov pytest-cov
script:
    - py.test -v --cov=./ tests
after_success:
    - codecov
